version: '3.8'

services:
#добавить сохранение данных при перезапуске
  postgres:
    image: postgres:15-alpine
    container_name: project_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME:-golang}
    volumes:
      - './docker/postgres/init.sql:/docker-entrypoint-initdb.d/'
    ports:
      - '5432:5432'
